### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by 3eif** [Politiwatch/PrivacySpy-API#1]
Hello. When I try to make a GET request, I get an Internal Server Error. Here is my code:
```
    await axios.get(
        baseURL,
        {
            method: 'GET',
            params: {
                token: 'privacyspy_token',
                url: 'application/x-www-form-urlencoded',
            }
        },
    ).then(function (res) {
        console.log(res);
    }).catch(function (error) {
        console.log(error);
    });

**Comment by ibarakaiev** [comment]
Hi @Tetracyl, PrivacySpy NLP API has been shut down with the release of [new PrivacySpy](https://privacyspy.org/) version yesterday, although I think you wouldn't be able to access it with your code anyway since `privacyspy_token` is an environment variable. Please take a look at [our new API](https://privacyspy.org/api/) and let me know if you have any questions.

**Comment by 3eif** [comment]
I'll use the new API then, thanks!
